#!/usr/bin/env python3
"""
Project Initialization Script
Creates the specific folder structure required by the analysis scripts
and verifies that XFOIL and Python libraries are installed.
"""

import os
import sys
import shutil

def check_dependencies():
    print(f"[{'='*10} Dependency Check {'='*10}]")
    
    dependencies = ['numpy', 'matplotlib', 'scipy', 'pandas']
    missing = []
    
    for dep in dependencies:
        try:
            __import__(dep)
            print(f" [✓] {dep:<15} found")
        except ImportError:
            missing.append(dep)
            print(f" [✗] {dep:<15} MISSING")
    
    # Check XFOIL
    print("\n--- Checking System Binaries ---")
    xfoil_path = shutil.which('xfoil')
    
    if xfoil_path:
        print(f" [✓] XFOIL found at: {xfoil_path}")
    else:
        # Check for local windows executable in current folder
        if os.path.exists("xfoil.exe"):
             print(f" [✓] XFOIL found (Local xfoil.exe)")
        else:
            print(" [✗] XFOIL not found in system PATH")
            print("     -> Linux/WSL: Run 'sudo apt-get install xfoil'")
            print("     -> Windows: Download from https://web.mit.edu/drela/Public/web/xfoil/")
            print("                 and place 'xfoil.exe' in this folder.")

    return missing

def create_structure():
    """Create project folder structure based on the scripts used"""
    print(f"\n[{'='*10} Creating Directories {'='*10}]")
    
    # These match the paths used in your analysis scripts
    folders = [
        'airfoil_data_clean',    # For raw generated files
        'airfoil_data_refined',  # For smoothed B-spline files
        'scripts',               # For your python code
        'results/xfoil_results/polar_files',
        'results/xfoil_results/summary_plots',
        'results/xfoil_results/reports',
        'results/plots_separated',
        'results/comparisons_full'
    ]
    
    for folder in folders:
        try:
            os.makedirs(folder, exist_ok=True)
            print(f" [✓] Created: {folder}/")
        except Exception as e:
            print(f" [✗] Error creating {folder}: {e}")

    # Create a placeholder README in data folders if they are empty
    readme_path = 'airfoil_data_refined/README.txt'
    if not os.path.exists(readme_path):
        with open(readme_path, 'w') as f:
            f.write("This folder will contain refined .dat files generated by '2_refine_airfoils.py'.\n")

if __name__ == "__main__":
    create_structure()
    
    missing = check_dependencies()
    
    print(f"\n[{'='*10} Status Report {'='*10}]")
    if missing:
        print("⚠️  Missing Python dependencies.")
        print(f"   Run: pip install {' '.join(missing)}")
    else:
        print("✅ System ready for analysis.")
    
    print("\nNext Steps:")
    print("1. Put your scripts in the 'scripts/' folder.")
    print("2. Run 'python scripts/1_generate_naca_files.py'")
    print("3. Run 'python scripts/2_refine_airfoils.py'")
    print("4. Run 'python scripts/3_xfoil_analyzer.py'")
    print("5. Run 'python scripts/5_plots.py'")